name: CD on AWS S3
on:
  push:
    branches: [master]
jobs:
  build-deploy:
    name: Deploy Prod to S3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_PROD_BUCKET }}
      PATHS: '/*'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy on AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks
        env:
          SOURCE_DIR: './build/'
          DEST_DIR: ''
