name: iTunes Music Finder CI
on:
  pull_request:
    branches: [master]
jobs:
  build-lint-test:
    name: Build Lint Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Test code
        run: yarn test

      - name: Build application
        run: yarn build

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
