name: Deploy to S3 on PR

on:
  pull_request:
    branches: [master]

jobs:
  s3_deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      PATHS: '/*'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: vars
        run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: export BRANCH_NAME=${{ steps.vars.outputs.branch }} && yarn build:uat

      - name: S3 Deploy
        run: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks
        env:
          SOURCE_DIR: './build/'
          DEST_DIR: ${{ steps.vars.outputs.branch }}
